import com.lambdaworks.crypto.SCryptUtil;
import java.sql.*;
import javax.swing.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabri
 */
public class Administrador extends javax.swing.JDialog {

    /**
     * Creates new form Administrador
     */
    public Administrador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Administrar usuarios");
        llenarLista();
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        Sql sql = new Sql();
        sql.conectar();
        ResultSet usuarios = sql.select("*", "usuarios");
        try{
            //usuarios.next();
            if(!usuarios.next()){
                this.chbEmpleadoA.setEnabled(false);
            }
            sql.desconectar();
        }catch(SQLException ex){
            
        }
    }
    
    public void llenarLista(){
        try{
            Sql sql = new Sql();
            sql.conectar();
            ResultSet datos = sql.select("usuario", "usuarios");
            DefaultListModel model = new DefaultListModel();
            lstUsuariosA.setModel(model);
            
            //model.setRowCount(0);
            while(datos.next()){
                model.addElement(datos.getString("usuario"));
            }
            System.out.println("Seleccion exitosa");
            sql.desconectar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al seleccionar \n"+ex,"Error",3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgRolA = new javax.swing.ButtonGroup();
        bgSexoA = new javax.swing.ButtonGroup();
        rbOtroA = new javax.swing.JRadioButton();
        rbFemA = new javax.swing.JRadioButton();
        rbMascA = new javax.swing.JRadioButton();
        chbEmpleadoA = new javax.swing.JCheckBox();
        chbAdminA = new javax.swing.JCheckBox();
        lblUsuarioA = new javax.swing.JLabel();
        txtUsuarioA = new javax.swing.JTextField();
        lblPassR = new javax.swing.JLabel();
        pswPassA = new javax.swing.JPasswordField();
        lblNombreA = new javax.swing.JLabel();
        txtNombreA = new javax.swing.JTextField();
        lblApellidoA = new javax.swing.JLabel();
        txtApellidoA = new javax.swing.JTextField();
        lblRutA = new javax.swing.JLabel();
        txtRutA = new javax.swing.JTextField();
        lblEdadA = new javax.swing.JLabel();
        jsEdadA = new javax.swing.JSpinner();
        lblRoA = new javax.swing.JLabel();
        lblSexoA = new javax.swing.JLabel();
        btnEliminarA = new javax.swing.JButton();
        btnSalirA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstUsuariosA = new javax.swing.JList<>();
        lblTituloA = new javax.swing.JLabel();
        btnModificarA = new javax.swing.JButton();
        btnGuardarA1 = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        bgSexoA.add(rbOtroA);
        rbOtroA.setText("Otro");

        bgSexoA.add(rbFemA);
        rbFemA.setText("Femenino");

        bgSexoA.add(rbMascA);
        rbMascA.setText("Masculino");

        bgRolA.add(chbEmpleadoA);
        chbEmpleadoA.setText("Empleado");

        bgRolA.add(chbAdminA);
        chbAdminA.setText("Administrador");

        lblUsuarioA.setText("Usuario");

        txtUsuarioA.setNextFocusableComponent(pswPassA);

        lblPassR.setText("Contraseña");

        lblNombreA.setText("Nombre");

        lblApellidoA.setText("Apellido");

        lblRutA.setText("Rut");

        lblEdadA.setText("Edad");

        lblRoA.setText("Rol");

        lblSexoA.setText("Sexo");

        btnEliminarA.setText("Eliminar");
        btnEliminarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAActionPerformed(evt);
            }
        });

        btnSalirA.setText("Salir");
        btnSalirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAActionPerformed(evt);
            }
        });

        lstUsuariosA.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstUsuariosA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstUsuariosAMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstUsuariosA);

        lblTituloA.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lblTituloA.setText("Administrador");

        btnModificarA.setText("Modificar");
        btnModificarA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarAActionPerformed(evt);
            }
        });

        btnGuardarA1.setText("Guardar");
        btnGuardarA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarA1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreA)
                            .addComponent(lblApellidoA)
                            .addComponent(lblRutA)
                            .addComponent(lblEdadA)
                            .addComponent(lblRoA)
                            .addComponent(lblSexoA))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRutA, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jsEdadA, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnModificarA)
                                            .addComponent(chbAdminA))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(chbEmpleadoA)
                                            .addComponent(btnGuardarA1))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbFemA)
                                    .addComponent(rbMascA)
                                    .addComponent(rbOtroA))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblUsuarioA)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassR)
                                .addGap(5, 5, 5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pswPassA)
                            .addComponent(txtUsuarioA, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSalirA, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarA)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloA)
                .addGap(162, 162, 162))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {pswPassA, txtApellidoA, txtNombreA, txtRutA, txtUsuarioA});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTituloA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsuarioA)
                            .addComponent(txtUsuarioA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPassR)
                            .addComponent(pswPassA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreA)
                            .addComponent(txtNombreA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblApellidoA)
                            .addComponent(txtApellidoA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblRutA)
                            .addComponent(txtRutA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEdadA)
                            .addComponent(jsEdadA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(chbAdminA)
                            .addComponent(lblRoA)
                            .addComponent(chbEmpleadoA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(rbMascA)
                            .addComponent(lblSexoA))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbFemA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbOtroA)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnModificarA)
                            .addComponent(btnGuardarA1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addComponent(btnSalirA))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAActionPerformed
        Sql sql = new Sql();
        sql.conectar();
        if (lstUsuariosA.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario","Error",3);
        }else{
           sql.delete("usuarios", "usuario", lstUsuariosA.getSelectedValue()); 
        }
        
        sql.desconectar();
        llenarLista();
        clear();
        
    }//GEN-LAST:event_btnEliminarAActionPerformed
    
    public void cerrar(){
        Sql sql = new Sql();
        sql.conectar();
        ResultSet usuarios = sql.select("*", "usuarios");
        String botones[]  ={ "Aceptar", "Cancelar"};
        try{
            if(!usuarios.next()){
                String texto  = "Base de datos vacia, si cierra la ventana no podrá iniciar sesion con ningun usuario";
                int eleccion = JOptionPane.showOptionDialog(this, texto, "ATENCIÓN", 0, 0, null, botones, this);
                System.out.println(eleccion);
                if(eleccion == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }else{
                this.dispose();
            }
        }catch(SQLException ex){
            
        }
        sql.desconectar();
    }
    private void btnSalirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAActionPerformed
        cerrar();
    }//GEN-LAST:event_btnSalirAActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrar();
    }//GEN-LAST:event_formWindowClosing

    private void lstUsuariosAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstUsuariosAMouseClicked
        String item = lstUsuariosA.getSelectedValue();
        String usuario="",nombre="",apellido="",rut="";
        char sexo=' ';
        byte edad=0,rol=0;
        Sql sql = new Sql();
        sql.conectar();
        
        ResultSet datos = sql.where("usuarios", "usuario", item);
        try{
            while(datos.next()){
                usuario = datos.getString("usuario");
                nombre = datos.getString("nombre");
                apellido  = datos.getString("apellido");
                rut = datos.getString("rut");
                sexo = datos.getString("sexo").charAt(0);
                edad  = datos.getByte("edad");
                rol = datos.getByte("rol");
            }
            sql.desconectar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Usuario no valido \n"+ex,"Error",3);
        }
        txtUsuarioA.setText(usuario);
        txtNombreA.setText(nombre);
        txtApellidoA.setText(apellido);
        txtRutA.setText(rut);
        if (sexo == 'M'){
            rbMascA.setSelected(true);
        }else{
            rbFemA.setSelected(true);
        }
        jsEdadA.setValue(edad);
        if(rol==0){
            chbAdminA.setSelected(true);
        }else{
            chbEmpleadoA.setSelected(true);
        }
    }//GEN-LAST:event_lstUsuariosAMouseClicked

    private void btnModificarAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarAActionPerformed
        Sql sql = new Sql();
        byte rol= 0;
        char sexo=' ';
        
        if(chbAdminA.isSelected()){
            rol = 0;
        }else{
           rol = 1;
        }

        if(rbMascA.isSelected()){
            sexo = rbMascA.getText().charAt(0);
        }else{
            if(rbOtroA.isSelected()){
                sexo = rbOtroA.getText().charAt(0);

            }else{
                sexo = rbFemA.getText().charAt(0);
            }
        }
        sql.conectar();
        if (lstUsuariosA.isSelectionEmpty()){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un usuario","Error",3);
        }else{
            String contraseña =pswPassA.getText();
            String hash = SCryptUtil.scrypt(contraseña, 16,16,16);
            String sentencia = "UPDATE usuarios SET usuario = '"+
                    txtUsuarioA.getText()+
                    "', password = '"+hash+
                    "', nombre = '"+txtNombreA.getText()+
                    "', apellido = '"+txtApellidoA.getText()+
                    "', rut = '"+txtRutA.getText()+
                    "', edad = "+jsEdadA.getValue()+
                    ", rol = "+rol+
                    ", sexo = '"+sexo+"' WHERE usuario = '"+lstUsuariosA.getSelectedValue()+"'";
            sql.sentence(sentencia);
        }
        sql.desconectar();
        llenarLista();
        clear();

    }//GEN-LAST:event_btnModificarAActionPerformed

    private void btnGuardarA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarA1ActionPerformed
        String usuario = txtUsuarioA.getText();
        String contraseña = pswPassA.getText();
        String nombre = txtNombreA.getText();
        String apellido = txtApellidoA.getText();
        String rut = txtRutA.getText();
        byte edad = Byte.parseByte(jsEdadA.getValue().toString());
        byte rol = 0;
        String hash = SCryptUtil.scrypt(contraseña, 16,16,16);
        
        if(chbAdminA.isSelected()){
            rol = 0;
        }else{
           rol = 1;
        }
        char sexo=' ';
        
        if(rbMascA.isSelected()){
            sexo = rbMascA.getText().charAt(0);
        }else{
            if(rbOtroA.isSelected()){
                sexo = rbOtroA.getText().charAt(0);

            }else{
                sexo = rbFemA.getText().charAt(0);
            }
        }
        String insert="INSERT INTO usuarios VALUES ('"+ usuario +"','"+ hash +"','"+nombre+"','"+apellido+"','"+rut+"','"+sexo+"',"+edad+","+rol+")";
        Sql sql = new Sql();
        sql.conectar();
        
        sql.sentence(insert);
        sql.desconectar();
        llenarLista();
        clear();
    
    }//GEN-LAST:event_btnGuardarA1ActionPerformed

    public void clear(){
        txtUsuarioA.setText("");
        txtNombreA.setText("");
        pswPassA.setText("");
        txtApellidoA.setText("");
        txtRutA.setText("");
        bgRolA.clearSelection();
        jsEdadA.setValue(0);
        bgSexoA.clearSelection();
        
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Administrador dialog = new Administrador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgRolA;
    private javax.swing.ButtonGroup bgSexoA;
    private javax.swing.JButton btnEliminarA;
    private javax.swing.JButton btnGuardarA1;
    private javax.swing.JButton btnModificarA;
    private javax.swing.JButton btnSalirA;
    private javax.swing.JCheckBox chbAdminA;
    private javax.swing.JCheckBox chbEmpleadoA;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsEdadA;
    private javax.swing.JLabel lblApellidoA;
    private javax.swing.JLabel lblEdadA;
    private javax.swing.JLabel lblNombreA;
    private javax.swing.JLabel lblPassR;
    private javax.swing.JLabel lblRoA;
    private javax.swing.JLabel lblRutA;
    private javax.swing.JLabel lblSexoA;
    private javax.swing.JLabel lblTituloA;
    private javax.swing.JLabel lblUsuarioA;
    private javax.swing.JList<String> lstUsuariosA;
    private javax.swing.JPasswordField pswPassA;
    private javax.swing.JRadioButton rbFemA;
    private javax.swing.JRadioButton rbMascA;
    private javax.swing.JRadioButton rbOtroA;
    private javax.swing.JTextField txtApellidoA;
    private javax.swing.JTextField txtNombreA;
    private javax.swing.JTextField txtRutA;
    private javax.swing.JTextField txtUsuarioA;
    // End of variables declaration//GEN-END:variables
}
