import java.sql.*;
import javax.swing.*;
import com.lambdaworks.crypto.SCryptUtil;
/**
 *
 * @author gabri
 */
public class Usuario extends javax.swing.JFrame{
    
    
    /**
     * Creates new form Usuario
     */
    public Usuario() {
        initComponents();
        fullCombo();
        this.setTitle("Iniciar Sesión");
        Sql sql = new Sql();
        sql.conectar();
        
        ResultSet usuarios = sql.select("*", "usuarios");

        try{
            //usuarios.next();
            if(!usuarios.next()){
                Administrador admin = new Administrador(this,true);;
                admin.setVisible(true);
                this.setVisible(false);
            }
            sql.desconectar();
        }catch(SQLException ex){
           System.out.println("No esxiste usuario en bd"); 
        }
    }
    public static String nombre="";
    public static boolean admin = true;
    public static char sexo = ' ';
    public void fullCombo(){
        try{
            Sql sql = new Sql();
            sql.conectar();
            cbUsuarios.removeAllItems();
           
            ResultSet lista = sql.select("usuario", "usuarios");
            while(lista.next()){
                cbUsuarios.addItem(lista.getString("usuario"));
            }
            System.out.println("Seleccion exitosa");
            sql.desconectar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al seleccionar \n"+ex,"Error",3);
        }
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblTituloU = new javax.swing.JLabel();
        lblPass = new javax.swing.JLabel();
        pswPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();
        cbUsuarios = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNombre.setText("Usuario");

        lblTituloU.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lblTituloU.setText("Usuarios");

        lblPass.setText("Contraseña");

        btnIngresar.setText("Ingresar");
        btnIngresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        cbUsuarios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbUsuariosFocusGained(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNombre)
                                    .addComponent(lblPass))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pswPass)
                                    .addComponent(cbUsuarios, 0, 154, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTituloU)
                                .addGap(60, 60, 60))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnIngresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnIngresar, btnSalir});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTituloU, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPass)
                    .addComponent(pswPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnSalir))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        Sql sql = new Sql();
        String contr="";
        byte rol=0;
        sql.conectar();
        String sentencia = "select password,rol,nombre,apellido,sexo from usuarios where usuario = '"+
                cbUsuarios.getSelectedItem().toString()+"'";
        ResultSet datos = sql.select(sentencia);
        
        try{
            while(datos.next()){

                contr = datos.getString("password");
                rol = datos.getByte("rol");
                nombre = datos.getString("nombre") + " " + datos.getString("apellido");
                sexo = datos.getString("sexo").charAt(0);
     
            }
            boolean validate = SCryptUtil.check(pswPass.getText(), contr);
            if (validate){
                System.out.println("Login correcto");
 
                if (rol != 0){
                    admin = false;
                }
                
                Principal principal = new Principal();
                //this.dispose();
                principal.setVisible(true);
                //this.setVisible(false);
 
            }else{
                JOptionPane.showMessageDialog(null,"Usuario y/o contraseña incorrectos \n","Error",3);
                pswPass.setText("");
                pswPass.requestFocus();
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"No ha sido posible acceder a los registros \n"+ex,"Error",3);
        }
        sql.desconectar();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        
        System.exit(0);
         
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbUsuariosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbUsuariosFocusGained
         this.fullCombo();
    }//GEN-LAST:event_cbUsuariosFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbUsuarios;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPass;
    private javax.swing.JLabel lblTituloU;
    private javax.swing.JPasswordField pswPass;
    // End of variables declaration//GEN-END:variables
}
