
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author gabri
 */
public class Categoria extends javax.swing.JDialog {
    
    /**
     * Creates new form Categoria
     */
    public Categoria(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarLista();
        this.setTitle("Categorias");
        
        
    }
    public void llenarLista(){
        try{
            Sql sql = new Sql();
            sql.conectar();
            ResultSet datos = sql.select("*", "categorias");
            DefaultListModel model = new DefaultListModel();
            lstCategC.setModel(model);
            
            //model.setRowCount(0);
            while(datos.next()){
                model.addElement(datos.getString("codigo")+" "+ datos.getString("nombre"));
            }
            System.out.println("Seleccion exitosa");
            sql.desconectar();
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null, "Error al seleccionar \n"+ex,"Error",3);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCategC = new javax.swing.JList<>();
        lblCodC = new javax.swing.JLabel();
        txtCodC = new javax.swing.JTextField();
        lblNombreC = new javax.swing.JLabel();
        btnAgregarC = new javax.swing.JButton();
        txtNombreC = new javax.swing.JTextField();
        btnEliminarC = new javax.swing.JButton();
        btnAtrasC = new javax.swing.JButton();
        btnModificarC = new javax.swing.JButton();
        btnDeshacerC = new javax.swing.JButton();
        lblTituloC = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lstCategC.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCategC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstCategCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstCategC);

        lblCodC.setText("Codigo");

        lblNombreC.setText("Nombre");

        btnAgregarC.setText("Agregar");
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });

        btnEliminarC.setText("Eliminar");
        btnEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCActionPerformed(evt);
            }
        });

        btnAtrasC.setText("Atrás");
        btnAtrasC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasCActionPerformed(evt);
            }
        });

        btnModificarC.setText("Modificar");

        btnDeshacerC.setText("Deshacer");
        btnDeshacerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeshacerCActionPerformed(evt);
            }
        });

        lblTituloC.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        lblTituloC.setText("Categoria");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(lblTituloC))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAtrasC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNombreC)
                                            .addComponent(lblCodC))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCodC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(txtNombreC)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAgregarC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnModificarC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEliminarC))
                                    .addComponent(btnDeshacerC, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAgregarC, btnAtrasC, btnDeshacerC, btnEliminarC, btnModificarC});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTituloC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCodC)
                            .addComponent(txtCodC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreC)
                            .addComponent(txtNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeshacerC)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregarC)
                            .addComponent(btnModificarC)
                            .addComponent(btnEliminarC)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAtrasC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAgregarC, btnAtrasC, btnDeshacerC, btnEliminarC, btnModificarC});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
        String codigo = txtCodC.getText();
        String nombre = txtNombreC.getText();
        
        String insert="INSERT INTO categorias VALUES ('"+ codigo+"','"+nombre+"')";
        Sql sql = new Sql();
        sql.conectar();
        sql.sentence(insert);
        sql.desconectar();
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void btnAtrasCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasCActionPerformed
        //this.dispose();
        this.setVisible(false);
    }//GEN-LAST:event_btnAtrasCActionPerformed

    private void btnDeshacerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeshacerCActionPerformed
       txtCodC.setText("");
       txtNombreC.setText("");
       txtCodC.requestFocus();
    }//GEN-LAST:event_btnDeshacerCActionPerformed

    private void lstCategCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstCategCMouseClicked
       
       String item = lstCategC.getSelectedValue();
       txtCodC.setText(item.substring(0, item.indexOf(" ")));
       txtNombreC.setText(item.substring(item.indexOf(" "),item.length()));
    }//GEN-LAST:event_lstCategCMouseClicked

    private void btnEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCActionPerformed
        //int fila = lstCategC.getSelectedIndex();
        //String valor=lstCategC.
        //Sql sql = new Sql();
        //sql.conectar();
        //sql.delete("categorias","codigo",valor);
        //sql.desconectar();
        
    }//GEN-LAST:event_btnEliminarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Categoria dialog = new Categoria(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarC;
    private javax.swing.JButton btnAtrasC;
    private javax.swing.JButton btnDeshacerC;
    private javax.swing.JButton btnEliminarC;
    private javax.swing.JButton btnModificarC;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodC;
    private javax.swing.JLabel lblNombreC;
    private javax.swing.JLabel lblTituloC;
    private javax.swing.JList<String> lstCategC;
    private javax.swing.JTextField txtCodC;
    private javax.swing.JTextField txtNombreC;
    // End of variables declaration//GEN-END:variables
}
